### ISSUE TITLE
SSL certification problem

### ISSUE THREAD

**Issue by MaxMuehlbauer** [glotcode/glot#30]
Hi, I am trying to create snippets with your API described [at glot-snippets](https://github.com/prasmussen/glot-snippets/blob/master/api_docs/create_snippet.md).

Using the example bash code you have provided I get following error:
![image](https://user-images.githubusercontent.com/18306885/107420066-c85f2d80-6b18-11eb-91c2-334f7acfdf1f.png)

Also when requested from a Node.js function, I get this error:
![image](https://user-images.githubusercontent.com/18306885/107420226-f5134500-6b18-11eb-8d8c-71daa65d92d8.png)

I did a little research and everything I found hints to a misconfiguration on your server. Could you maybe take your time to look into the issue? 😊

Here's a very good StackOverflow answer for this topic which also includes further links https://stackoverflow.com/a/60020493

**Comment by prasmussen** [comment]
Thanks for reporting this! It should work now as far as I can tell.

Also note that the api recently changed url to https://glot.io/api/snippets
[Updated api docs](https://github.com/glotcode/glot/tree/master/api_docs/snippets)
