### ISSUE TITLE
Cant get output 

### ISSUE THREAD

**Issue by karimuddin-tech** [glotcode/glot#32]
{
stdout: "",
error: "",
stderr: ""
}
my code is :
 const glotData = {"files": [{"name": "main.py", "content": "print('Hello World!')"}]}

let data = JSON.stringify(glotData);
    glot.runCode("python",data,url, (response) =>{
        res.send(response)    
    });

getting empty object while run code ....
any help please

**Comment by prasmussen** [comment]
The only advice I can give based on the given information is for you to try to figure out how the http request you are sending looks like and compare it to the api docs.

**Comment by karimuddin-tech** [comment]
ooh thanks.
