### ISSUE TITLE
Zig support

### ISSUE THREAD

**Issue by perillo** [glotcode/glot#41]
Is it possible to add Zig support?

Currently Zig is still under development.  Development versions of Zig 0.10 are available on https://ziglang.org/download/.
The binary for Linux is statically linked.

Like Go, Zig supports the `zig run` command.
Zig logo is available at https://github.com/ziglang/logo.

Thanks.

**Comment by prasmussen** [comment]
Absolutely, zig has been on my list to add.
Only 0.9.1 is available in nix packages though, will that work for now?

**Comment by perillo** [comment]
@prasmussen It may not work with recent code, but it is better than nothing.

Since the release available from https://ziglang.org/download/ is statically linked, isn't it possible to just copy the latest release on the docker image?

Thanks.

**Comment by prasmussen** [comment]
Yeah, I want to avoid having to go the homepage of each language to check for new versions.

0.9.1 is now live: https://glot.io/new/zig
