### ISSUE TITLE
Cost and pricing?

### ISSUE THREAD

**Issue by ya332** [glotcode/glot#47]
Very impressive service. Quick question at the creator @prasmussen ? How are you able to keep this service as free?

**Comment by prasmussen** [comment]
I'm paying most of it myself.

Cost is around 40$/month.
I get 10-20$/month from ad revenue. I could probably get more if I had more intrusive/annoying ads.

**Comment by ya332** [comment]
How are you able to keep the cost that low? I see that you are storing the snippets.

**Comment by prasmussen** [comment]
Two small vm's on Linode have been able to handle the traffic so far.
According to GA there are around 15k monthly users.

**Comment by Dharani-gowtham** [comment]
hey buddy, i want to use your glot to a commercial purpose, which may hit around extra few thousand users around each week. then how can i use your glot? i wish i dont want to make it burden by adding extra cost to you. im too build my own server and having cloud too. is any other way to share your code?

**Comment by prasmussen** [comment]
Not sure what you are asking. All the code and docker images are open source and it's possible for anyone to deploy it.
I don't have the capacity to provide support beyond what's already in the README's.
